### ISSUE TITLE
Overwriting an item within a list crashes ansible

### ISSUE THREAD

**Issue by luto** [kwoodson/yedit#6]
Given the list `[1, 2, 3]`, this playbook should change it to `[5, 2, 3]`.

```yml
- hosts: localhost
  gather_facts: no
  tasks:

  - copy:
      dest: /tmp/test1.yml
      content: |
        - 1
        - 2
        - 3

  - name: overwrite first entry in list
    yedit:
      src: /tmp/test1.yml
      update: yes
      key: 0  # using `index` instead of `key` yields the same result
      value: 5
```

Instead it crashes ansible:

```
TASK [overwrite first entry in list] *******************************************
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/executor/process/result.py", line 143, in run
    elif result.is_failed():
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_result.py", line 56, in is_failed
    'results' in self._result and True in [True for x in self._result['results'] if 'failed_when_result' in x]:
TypeError: argument of type 'int' is not iterable
```

This only seems to affect lists. Overwriting a key within a dictionary works fine.

**Comment by luto** [comment]
The `exit_json()`-method always expects a list for the `results`-parameter. If it sees an object, it fails gracefully and wraps it automatically. If there is a list given, which is not a list of results, it fails hard.
